/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jsfcAvrT2gX1xBNiQzA5u6
// Component: QZa7Jb0w3J50
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import MenuStack from "../../MenuStack"; // plasmic-import: vfLBrX0fe4mB/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: jsfcAvrT2gX1xBNiQzA5u6/projectcss
import sty from "./PlasmicPublications.module.css"; // plasmic-import: QZa7Jb0w3J50/css

createPlasmicElementProxy;

export const PlasmicPublications__VariantProps = new Array();

export const PlasmicPublications__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPublications__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <section className={classNames(projectcss.all, sty.section__jieXf)}>
            <MenuStack
              data-plasmic-name={"menuStack"}
              data-plasmic-override={overrides.menuStack}
              className={classNames("__wab_instance", sty.menuStack)}
            />
          </section>
          <section className={classNames(projectcss.all, sty.section__qr4M)}>
            <h1
              data-plasmic-name={"h1"}
              data-plasmic-override={overrides.h1}
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1
              )}
            >
              {"Publications"}
            </h1>
            <div
              data-plasmic-name={"freeBox"}
              data-plasmic-override={overrides.freeBox}
              className={classNames(projectcss.all, sty.freeBox)}
            >
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link___8439Q
                )}
                component={Link}
                href={
                  "https://www.biorxiv.org/content/10.1101/2024.09.21.613770v1"
                }
                platform={"nextjs"}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{
                      color: "var(--token-8bvv-gBG7EgC)",
                      fontWeight: 700
                    }}
                  >
                    {"Hunt, J.B."}
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "var(--token-8bvv-gBG7EgC)" }}
                  >
                    {
                      ", Buteau, A., Hanson, S., Poleg-Polsky, A., Felsen, G. (2024). "
                    }
                  </span>
                  <React.Fragment>
                    {
                      "Neural substrates for saccadic modulation of visual representations in mouse superior colliculus."
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "var(--token-8bvv-gBG7EgC)" }}
                  >
                    {" "}
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{
                      fontStyle: "italic",
                      color: "var(--token-8bvv-gBG7EgC)"
                    }}
                  >
                    {"Biorxiv"}
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "var(--token-8bvv-gBG7EgC)" }}
                  >
                    {"."}
                  </span>
                </React.Fragment>
              </PlasmicLink__>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__uNi1I
                )}
                component={Link}
                href={"https://www.nature.com/articles/s41467-022-32761-8"}
                platform={"nextjs"}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "var(--token-8bvv-gBG7EgC)" }}
                  >
                    {"Gaynes, J.A., Budoff, S.A., Grybko, M.J., "}
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{
                      color: "var(--token-8bvv-gBG7EgC)",
                      fontWeight: 700
                    }}
                  >
                    {"Hunt, J.B."}
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "var(--token-8bvv-gBG7EgC)" }}
                  >
                    {", Poleg-Polsky, A. (2022)."}
                  </span>
                  <React.Fragment>
                    {
                      " Classical center-surround receptive fields facilitate novel object detection in retinal bipolar cells."
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "var(--token-8bvv-gBG7EgC)" }}
                  >
                    {" Nature Communications."}
                  </span>
                </React.Fragment>
              </PlasmicLink__>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__ec18Q
                )}
                component={Link}
                href={"https://www.nature.com/articles/s42003-021-02248-1"}
                platform={"nextjs"}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "var(--token-8bvv-gBG7EgC)" }}
                  >
                    {"Essig, J., "}
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{
                      color: "var(--token-8bvv-gBG7EgC)",
                      fontWeight: 700
                    }}
                  >
                    {"Hunt, J.B."}
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "var(--token-8bvv-gBG7EgC)" }}
                  >
                    {", Felsen, G. (2021). "}
                  </span>
                  <React.Fragment>
                    {
                      "Inhibitory neurons in the superior colliculus mediate selection of spatially-directed movements."
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "var(--token-8bvv-gBG7EgC)" }}
                  >
                    {" "}
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{
                      fontStyle: "italic",
                      color: "var(--token-8bvv-gBG7EgC)"
                    }}
                  >
                    {"Communications Biology"}
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "var(--token-8bvv-gBG7EgC)" }}
                  >
                    {". "}
                  </span>
                </React.Fragment>
              </PlasmicLink__>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link___09YtE
                )}
                component={Link}
                href={
                  "https://journals.lww.com/behaviouralpharm/abstract/2017/06000/subchronic_anesthetic_ketamine_injections_in_rats.7.aspx"
                }
                platform={"nextjs"}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "var(--token-8bvv-gBG7EgC)" }}
                  >
                    {"Pickens, C.L., Aurand, L., "}
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{
                      color: "var(--token-8bvv-gBG7EgC)",
                      fontWeight: 700
                    }}
                  >
                    {"Hunt, J.B."}
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "var(--token-8bvv-gBG7EgC)" }}
                  >
                    {", Fisher, H. (2017). "}
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "var(--token-3BYo9Vr4LmDZ)" }}
                  >
                    {
                      "Subchronic anesthetic ketamine injections in rats impair choice reversal learning, but have no effect on reinforcer devaluation."
                    }
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "var(--token-8bvv-gBG7EgC)" }}
                  >
                    {" "}
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{
                      color: "var(--token-8bvv-gBG7EgC)",
                      fontStyle: "italic"
                    }}
                  >
                    {"Behavioural Pharmacology."}
                  </span>
                </React.Fragment>
              </PlasmicLink__>
            </div>
          </section>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "menuStack", "h1", "freeBox"],
  menuStack: ["menuStack"],
  h1: ["h1"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPublications__ArgProps,
          internalVariantPropNames: PlasmicPublications__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPublications__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPublications";
  } else {
    func.displayName = `PlasmicPublications.${nodeName}`;
  }
  return func;
}

export const PlasmicPublications = Object.assign(
  // Top-level PlasmicPublications renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    menuStack: makeNodeComponent("menuStack"),
    h1: makeNodeComponent("h1"),
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicPublications
    internalVariantProps: PlasmicPublications__VariantProps,
    internalArgProps: PlasmicPublications__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPublications;
/* prettier-ignore-end */
